### ISSUE TITLE
pytest_patterns/test is missing

### ISSUE THREAD

**Issue by jchain** [smarie/pytest-patterns#6]
README mentions how to run like `pytest -v pytest_patterns/test` but the target folder is missing. When I run `pytest -v pytest_patterns` it says `fixture 'module_results_df' not found`

**Comment by smarie** [comment]
Hi @jchain , sorry for answering so late. Indeed the readme is completely wrong here. Please have a look at https://smarie.github.io/pytest-patterns/examples/data_science_benchmark/#executing-the-example
